:output:
  User:
    :options:
      :fields:
        - id
        - fname
        - lname
        - email
        - admin
        - banned
        - created_at
        - updated_at
  Post:
    :options:
      :fields:
        - id
        - title
        - content
        - user_id
